version: '3.9'
services:
  web-server:
    image: nginx:1.24.0
    container_name: '${APP_NAME}-nginx'
    ports:
      - '${APP_PORT}:80'
    networks:
      - techtext-network
    volumes:
      - ./devops/server/:/etc/nginx/conf.d/
      - ./:/var/www

  php:
    build:
      dockerfile: ./php.dockerfile
      context: .
    image: php:8.2-fpm
    container_name: '${APP_NAME}-php'
    volumes: 
      - ./:/var/www
    ports: 
      - "9000:9000"
    networks: 
      - techtext-network

  db:
    image: mysql:8.0.35
    container_name: '${APP_NAME}-mysql'
    volumes: 
      - ./devops/mysql_db:/var/lib/mysql    
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${DB_PORT}:3306'
    networks: 
      - techtext-network

networks: 
  techtext-network:
    driver: bridge
          